import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;
public class TreeTest {
    @Test
    public void testIsEmptyTrue() {
        Tree t1 = new Tree();
        assertTrue(t1.isEmpty());
    }

    @Test
    public void testIsEmptyFalse() {
        Tree t2 = new Tree(3);
        assertFalse(t2.isEmpty());
    }

    @Test
    public void testGetSize0() {
        Tree t1 = new Tree();
        assertEquals(0, t1.getSize());
    }

    @Test
    public void testGetSize3() {
        Tree t0 = new Tree(1);
        ArrayList<Tree> tmp = new ArrayList<>();
        tmp.add(t0);
        Tree t1 = new Tree(4);
        tmp.add(t1);
        Tree t2 = new Tree(3,  tmp);
        assertEquals(3, t2.getSize());
    }

    @Test
    public void testCount() {
        Tree t0 = new Tree(1);
        ArrayList<Tree> tmp = new ArrayList<>();
        tmp.add(t0);
        Tree t1 = new Tree(4);
        tmp.add(t1);
        Tree t = new Tree(3,  tmp);
        assertEquals(1, t.count(3));
        assertEquals(0, t.count(100));
    }

    @Test
    public void testAverage() {
        /*
        TODO: this is generated by GPT-5 So please check if it is same as python test
         */
        // empty tree
        Tree empty = new Tree(null, new ArrayList<>());
        assertEquals(0.0, empty.average(), 0.0001);

        // t = Tree(13, [Tree(2, []), Tree(6, [])])
        Tree t = new Tree(13, new ArrayList<>(Arrays.asList(
                new Tree(2),
                new Tree(6)
        )));
        assertEquals(7.0, t.average(), 0.0001);

        // lt = Tree(2, [Tree(4, []), Tree(5, [])])
        Tree lt = new Tree(2, new ArrayList<>(Arrays.asList(
                new Tree(4),
                new Tree(5)
        )));

        // rt = Tree(3, [Tree(6, []), Tree(7, []), Tree(8, []), Tree(9, []), Tree(10, [])])
        Tree rt = new Tree(3, new ArrayList<>(Arrays.asList(
                new Tree(6),
                new Tree(7),
                new Tree(8),
                new Tree(9),
                new Tree(10)
        )));

        // t = Tree(1, [lt, rt])
        Tree t2 = new Tree(1, new ArrayList<>(Arrays.asList(lt, rt)));
        assertEquals(5.5, t2.average(), 0.0001);
    }

    @Test
    public void testContains() {
        Tree t = new Tree(1, new ArrayList<>(Arrays.asList(
                new Tree(2),
                new Tree(5)
        )));
        assertTrue(t.contains(1));
        assertTrue(t.contains(5));
        assertFalse(t.contains(4));
    }

    @Test
    public void testLeaves() {
        // empty tree
        Tree empty = new Tree(null, new ArrayList<>());
        assertEquals(new ArrayList<Integer>(), empty.leaves());

        // t = Tree(1, [Tree(2, []), Tree(5, [])])
        Tree t1 = new Tree(1, new ArrayList<>(Arrays.asList(
                new Tree(2),
                new Tree(5)
        )));
        assertEquals(Arrays.asList(2, 5), t1.leaves());

        // lt = Tree(2, [Tree(4, []), Tree(5, [])])
        Tree lt = new Tree(2, new ArrayList<>(Arrays.asList(
                new Tree(4),
                new Tree(5)
        )));

        // rt = Tree(3, [Tree(6, []), Tree(7, [])])
        Tree rt = new Tree(3, new ArrayList<>(Arrays.asList(
                new Tree(6),
                new Tree(7)
        )));

        // t = Tree(1, [lt, rt])
        Tree t2 = new Tree(1, new ArrayList<>(Arrays.asList(lt, rt)));
        assertEquals(Arrays.asList(4, 5, 6, 7), t2.leaves());
    }


    @Test
    public void testDeleteItem() {
        // empty tree
        Tree empty = new Tree(null, new ArrayList<>());
        assertFalse(empty.deleteItem(99));

        // lt = Tree(2, [Tree(4, []), Tree(5, [])])
        Tree lt = new Tree(2, new ArrayList<>(Arrays.asList(
                new Tree(4),
                new Tree(5)
        )));

        // rt = Tree(3, [Tree(6, []), Tree(7, []), Tree(8, []), Tree(9, []),
        //               Tree(10, [Tree(11, [Tree(13, []), Tree(14, [])]),
        //                         Tree(12, [])])])
        Tree rt = new Tree(3, new ArrayList<>(Arrays.asList(
                new Tree(6),
                new Tree(7),
                new Tree(8),
                new Tree(9),
                new Tree(10, new ArrayList<>(Arrays.asList(
                        new Tree(11, new ArrayList<>(Arrays.asList(
                                new Tree(13),
                                new Tree(14)
                        ))),
                        new Tree(12)
                )))
        )));

        // t = Tree(1, [lt, rt])
        Tree t = new Tree(1, new ArrayList<>(Arrays.asList(lt, rt)));

        // tests
        assertFalse(t.deleteItem(99));
        assertTrue(t.deleteItem(3));
        assertFalse(t.contains(3));
    }


    @Test
    public void testInsert() {
        // case 1: empty tree, insert into it
        Tree t = new Tree(null, new ArrayList<>());
        t.insert(1);
        assertTrue(t.contains(1));

        // case 2: non-empty tree
        Tree lt = new Tree(2, new ArrayList<>(Arrays.asList(
                new Tree(4),
                new Tree(5)
        )));

        Tree rt = new Tree(3, new ArrayList<>(Arrays.asList(
                new Tree(6),
                new Tree(7),
                new Tree(8),
                new Tree(9),
                new Tree(10)
        )));

        Tree t2 = new Tree(1, new ArrayList<>(Arrays.asList(lt, rt)));
        t2.insert(100);
        assertTrue(t2.contains(100));
    }

}
